---
# Handle plugins
- name: "{{ startup_delay_s | default(10) }}s delay while starting Jenkins"
  wait_for: host={{ jenkins_host }} port={{ port }} delay={{ startup_delay_s | default(10) }}
  when: jenkins_install.changed or jenkins_http_config.changed or jenkins_init_prefix.changed

- name: "Create Jenkins CLI destination directory: {{ jenkins_dest }}"
  become: true
  file: path={{ jenkins_dest }} state=directory

- name: Get Jenkins CLI
  become: true
  get_url: url="{{ jenkins_api_url }}jnlpJars/jenkins-cli.jar" dest="{{ jenkins.cli_dest }}" mode=0440
  register: jenkins_local_cli
  until: "'OK' in jenkins_local_cli.msg or 'file already exists' in jenkins_local_cli.msg"
  retries: 5
  delay: 10

- name: Get Jenkins updates
  become: true
  get_url: url=http://updates.jenkins-ci.org/update-center.json dest={{ jenkins.updates_dest }} thirsty=yes mode=0440 timeout=30 use_proxy={{proxy}} validate_certs=False
  environment: proxy_env
  register: jenkins_updates
  when: proxy

- name: Get Jenkins updates without proxy
  become: true
  get_url: url=https://updates.jenkins-ci.org/update-center.json dest={{ jenkins.updates_dest }} thirsty=yes mode=0440 timeout=30 use_proxy={{proxy}} validate_certs=False
  register: jenkins_updates
  when: not proxy

- name: Update-center Jenkins
  become: true
  shell: "cat {{ jenkins.updates_dest }} | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- {{ jenkins_api_url }}updateCenter/byId/default/postBack"
  when: jenkins_updates.changed
  notify:
    - 'Restart Jenkins'
