---
jenkins_dest: /opt/jenkins
jenkins_lib: /var/lib/jenkins
jenkins:
  repo: 'deb http://pkg.jenkins-ci.org/debian binary/'
  dependencies:
    - '{{ java_version }}-jre'
    - '{{ java_version }}-jdk'
    - 'git'
    - 'curl'
  cli_dest: '{{ jenkins_dest }}/jenkins-cli.jar' # Jenkins CLI destination
  updates_dest: '{{ jenkins_dest }}/updates_jenkins.json' # Jenkins updates file
jenkins_host: "jenkins.dev"
jenkins_api_url: "http://{{jenkins_host}}:{{ port }}{{ prefix }}"
jenkins_cli_cmd: "java -jar {{ jenkins.cli_dest }} -s {{ jenkins_api_url }}"
jenkins_init_file: /etc/default/jenkins
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
jenkins_init_changes:
  - {option: "JENKINS_JAVA_OPTIONS", value: "{{ jenkins_java_options }}"}
