---
jenkins_dest: /opt/jenkins
jenkins_lib: /var/lib/jenkins
jenkins:
  repo: 'deb http://pkg.jenkins-ci.org/debian binary/'
  dependencies:
    - '{{ java_version }}-jre'
    - '{{ java_version }}-jdk'
    - 'git'
    - 'curl'
  cli_dest: '{{ jenkins_dest }}/jenkins-cli.jar'
  updates_dest: '{{ jenkins_dest }}/updates_jenkins.json'
jenkins_host: "jenkins.dev"
jenkins_api_url: "http://{{jenkins_host}}:{{ port }}{{ prefix }}"
jenkins_cli_cmd: "java -jar {{ jenkins.cli_dest }} -s {{ jenkins_api_url }}"
jenkins_init_file: /etc/default/jenkins
jenkins_init_changes:
  - {option: "JAVA_ARGS", value: "-Djenkins.install.runSetupWizard=false"}
