- name: add APT key
  become: true
  apt: >
    name=software-properties-common
    state=present

- name: add repository
  become: true
  apt_repository: >
    repo='ppa:ansible/ansible'
    state=present

- name: apt-get update
  become: true
  apt: update_cache=true

- name: install package
  become: true
  apt: >
    name=ansible
    state=present
