- name: add APT key
  become: true
  apt_key: >
    id=0x2C52609D
    keyserver=p80.pool.sks-keyservers.net
    state=present

- name: add repository
  become: true
  apt_repository: >
    repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
    state=present

- name: install package
  become: true
  apt: pkg=docker-engine

- name: start docker
  become: true
  service: >
    name=docker
    state=started

- name: add current user to group "docker"
  become: true
  user: >
    name={{ ansible_user_id }}
    groups=docker
    append=true

- name: install docker-py
  become: true
  pip: name=docker-py
