- name: install
  become: true
  apt: name=unattended-upgrades

- name: generate /etc/apt/apt.conf.d/20auto-upgrades
  become: true
  template: >
    src=20auto-upgrades.j2
    dest=/etc/apt/apt.conf.d/20auto-upgrades
    owner=root
    group=root
    mode=0644
  notify: restart unattended-upgrades
